[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version ="0.11.20" ,features = ["json", "blocking"]}
scraper = {version = "0.17.1" }
serde = {version =  "1.0.188"}
serde_json = {version = "1.0.107"}



